# Site settings
title: Portfolio Florent Duvillier
description: Portfolio Florent Duvillier
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Florent Duvillier
user_description: "I am a student in web development in my last year of bachelor at Sup'Internet. I'm passionate about design, new technologies and history, particularly that of the 19th and 20th century.
I'm currently in internship and looking for a job starting after the summer break."
user_title: Web developper
email: florentduvillier@hotmail.fr
twitter_username: lorem_ipsum
github_username:  gueguesix
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman